package interfaceGui;
public enum Elem_type {
	PAPER_COLLECTOR, GLASS_COLLECTOR, DEPOT, PACKAGE_COLLECTOR, DOMESTIC_COLLECTOR, PAPER_CONTAINER, GLASS_CONTAINER, PACKAGE_CONTAINER, DOMESTIC_CONTAINER, ROAD, WALKWAY
}
